outputs:
  - command: "baet --help"
    title: BAET
    img_paths:
      - docs/img/baet_help.svg

  - command: "baet extract --help"
    title: BAET
    img_paths:
      - docs/img/baet_extract_help.svg

  - command: "baet probe --help"
    title: BAET
    img_paths:
      - docs/img/baet_probe_help.svg
