target-version = "py312"
line-length = 120
src = ["src", "tests"]
fix = true

[format]
docstring-code-format = true

[lint]
extend-select = [
   "F", "I", "E", "W", "I", "D", "S", "G", "C4",
   "UP", "ANN", "B9", "A00", "PT", "Q0", "SIM", "RUF",

]
extend-ignore = [ "ANN101", "ANN401" ]
unfixable = ["B"]

[lint.per-file-ignores]
"src/BAET/cli/cli.py" = ["D102"]
"src/BAET/cli/commands/{extract,probe}.py" = ["D102"]
"tests/**" = ["S101", "D100", "D101", "D102", "D103"]

[lint.pydocstyle]
convention = "numpy"
