name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :0
      PYTEST_ADDOPTS: "--color=yes" # colors in pytest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.12"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install "poetry==1.7.*"
          poetry config virtualenvs.prefer-active-python true

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "poetry"

      #- name: Setup macOS PATH
      #  if: runner.os == 'macOS'
      #  run: |
      #    echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup cache variables
        shell: bash
        id: cache-vars
        run: |
          echo "date=$(/bin/date -u "+%m%w%Y")" >> $GITHUB_OUTPUT

      #- name: Install and cache ffmpeg (all OS)
      #  uses: FedericoCarboni/setup-ffmpeg@v2
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #  id: setup-ffmpeg

      - name: Run tests
        run: |
          poetry run python -m pytest
